### ISSUE TITLE
DATASETS  are not available for distribution

### ISSUE THREAD

**Issue by xiaolin96** [osllogon/epf-transformers#1]
File "E:\Anaconda\Prediction\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)

HTTPError: NOT FOUND

**Comment by osllogon** [comment]
Thank you for pointing this out, it seems that the url of the datasets from epftoolbox has now changed, I just fixed so with the new version there should not be any problem
